# Jekyll
permalink: /:categories/:title/
exclude: [release.sh]
markdown: redcarpet
name: PalletOps
highlighter: pygments
domain: palletops.com
cdn: http://67516654d2ef99c3042d-b9d92f522aee852c07f26ce9d1459c9c.r8.cf1.rackcdn.com
asset-ver: 20140617-02
gems:
  - jekyll-redirect-from
baseurl: /pallet
description: Pallet is a platform for agile and programmatic automation of 
   infrastructure in the cloud, on server racks or directly on virtual machines. 
